# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  CustomSharesConnector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        working-directory: ./connectors/CustomSharesConnector
        run: dotnet build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CustomSharesConnector
          path: ./connectors/CustomSharesConnector/bin/AnyCPU/Debug/CustomSharesConnector.mez
  PropertyDbConnector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        working-directory: ./connectors/PropertyDbConnector
        run: dotnet build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PropertyDbConnector
          path: ./connectors/PropertyDbConnector/bin/AnyCPU/Debug/PropertyDbConnector.mez
  custom-shares-viewer-visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./visuals/custom-shares-viewer-visual
        run: npm ci && npm install -g powerbi-visuals-tools
      - name: Build
        working-directory: ./visuals/custom-shares-viewer-visual
        run: npm run package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: custom-shares-viewer-visual
          path: ./visuals/custom-shares-viewer-visual/dist/*.pbiviz
  cached-derivs-viewer-visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./visuals/cached-derivs-viewer-visual
        run: npm ci && npm install -g powerbi-visuals-tools
      - name: Build
        working-directory: ./visuals/cached-derivs-viewer-visual
        run: npm run package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cached-derivs-viewer-visual
          path: ./visuals/cached-derivs-viewer-visual/dist/*.pbiviz
  create-release:
    name: Create New Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [CustomSharesConnector, PropertyDbConnector, custom-shares-viewer-visual, cached-derivs-viewer-visual]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: Roang-zero1/github-create-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v3
        with:
          args: "CustomSharesConnector/ PropertyDbConnector/ cached-derivs-viewer-visual/ custom-shares-viewer-visual/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}