# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# on:
#   push:
#     tags:
#       - 'v*'

on:
  push:
    branches:    
      - master

name: Run Test Builds

jobs:
  custom-shares-connector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        working-directory: ./connectors/CustomSharesConnector
        run: dotnet build
  property-db-connector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build
        working-directory: ./connectors/PropertyDbConnector
        run: dotnet build
  custom-shares-viewer-visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./visuals/custom-shares-viewer-visual
        run: npm ci
      - name: Build
        working-directory: ./visuals/custom-shares-viewer-visual
        run: npm run package
  cached-derivs-viewer-visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./visuals/cached-derivs-viewer-visual
        run: npm ci
      - name: Build
        working-directory: ./visuals/cached-derivs-viewer-visual
        run: npm run package
